[build]
  command = "scripts/build.js"
  publish = "build"

[[redirects]]
  from = "/Writing/UbuTrump/"
  to = "/features/ubu-trump/"
  status = 301

[[headers]]
  for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
