[build]
  command = "scripts/build.js"
  publish = "build"
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true


[[redirects]]
  from = "/Writing/UbuTrump"
  to = "/features/ubu-trump"
  status = 301
[[redirects]]
  from = "/Writing/UbuTrump/index.html"
  to = "/features/ubu-trump"
  status = 301

[[headers]]
  for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  X-Powered-By = "George Soros"
